name: Build app
run-name: ${{ github.actor }} build app
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.11.1
        with:
          gradle-version: 8.5
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Execute Gradle Build
        run: ./gradlew clean build


